import { invoke } from "@tauri-apps/api/core";
import type { Game, Note, Session, CreateGamePayload, UpdateGamePayload, ScanResult, AppSettings, ImportResult, FetchCoversResult, CoverCandidate, UpdateInfo, ModLoaderStatus, ModInfo, HltbData, WeeklyPlaytime, Collection, IgdbMetadata, LibraryGrowthEntry, SteamSyncResult, PullUninstalledResult, YearInReview } from "./types";

export const api = {
  getAllGames: () => invoke<Game[]>("get_all_games"),
  getGame: (id: string) => invoke<Game | null>("get_game", { id }),
  createGame: (payload: CreateGamePayload) => invoke<Game>("create_game", { payload }),
  updateGame: (payload: UpdateGamePayload) => invoke<Game>("update_game", { payload }),
  deleteGame: (id: string) => invoke<void>("delete_game", { id }),
  permanentDeleteGame: (id: string) => invoke<void>("permanent_delete_game", { id }),
  restoreGame: (id: string) => invoke<void>("restore_game", { id }),
  purgeTrash: () => invoke<number>("purge_trash"),
  getTrashedGames: () => invoke<Game[]>("get_trashed_games"),
  toggleFavorite: (id: string) => invoke<boolean>("toggle_favorite", { id }),
  togglePinned: (id: string) => invoke<boolean>("toggle_pinned", { id }),
  checkExeHealth: (id: string) => invoke<boolean>("check_exe_health", { id }),

  getNotes: (gameId: string) => invoke<Note[]>("get_notes", { gameId }),
  getSessions: (gameId: string) => invoke<Session[]>("get_sessions", { gameId }),
  createNote: (gameId: string, content: string) => invoke<Note>("create_note", { gameId, content }),
  updateNote: (id: string, content: string) => invoke<Note>("update_note", { id, content }),
  deleteNote: (id: string) => invoke<void>("delete_note", { id }),

  scanSteam: () => invoke<ScanResult>("scan_steam_games"),
  scanEpic: () => invoke<ScanResult>("scan_epic_games"),
  scanGog: () => invoke<ScanResult>("scan_gog_games"),
  scanAll: () => invoke<ScanResult>("scan_all_games"),
  scanFolder: (folderPath: string) => invoke<ScanResult>("scan_folder_for_games", { folderPath }),
  setGameCover: (gameId: string, imagePath: string) => invoke<string>("set_game_cover", { gameId, imagePath }),
  extractExeIcon: (exePath: string) => invoke<string>("extract_exe_icon", { exePath }),
  findCoverInDir: (dirPath: string) => invoke<string>("find_cover_in_dir", { dirPath }),
  readImageBase64: (filePath: string) => invoke<string>("read_image_base64", { filePath }),
  fetchUrlAsBase64: (url: string) => invoke<string>("fetch_url_as_base64", { url }),
  searchGameCovers: (query: string) => invoke<CoverCandidate[]>("search_game_covers", { query }),
  fetchMissingCovers: () => invoke<FetchCoversResult>("fetch_missing_covers"),
  getGameScreenshots: (steamAppId: string) => invoke<string[]>("get_game_screenshots", { steamAppId }),

  launchGame: (id: string) => invoke<void>("launch_game", { id }),
  launchSteamGame: (appId: string, gameId: string) => invoke<void>("launch_steam_game", { appId, gameId }),
  launchEpicGame: (appName: string, gameId: string) => invoke<void>("launch_epic_game", { appName, gameId }),
  openGameFolder: (id: string) => invoke<void>("open_game_folder", { id }),
  stopTracking: () => invoke<void>("stop_tracking"),
  stopGame: () => invoke<void>("stop_game"),

  getSettings: () => invoke<AppSettings>("get_settings"),
  saveSettings: (settings: AppSettings) => invoke<void>("save_settings", { settings }),
  exportLibrary: () => invoke<string>("export_library"),
  exportLibraryCsv: () => invoke<string>("export_library_csv"),
  exportGamesByIds: (ids: string[]) => invoke<string>("export_games_by_ids", { ids }),
  importLibrary: (path: string) => invoke<ImportResult>("import_library", { path }),
  saveFile: (path: string, content: string) => invoke<void>("save_file", { path, content }),
  checkForUpdate: () => invoke<UpdateInfo>("check_for_update", { ts: Date.now() }),
  openUrl: (url: string) => invoke<void>("open_url", { url }),
  isPortableMode: () => invoke<boolean>("is_portable_mode"),

  checkModloaderStatus: (installDir: string) => invoke<ModLoaderStatus>("check_modloader_status", { installDir }),
  installBepinex: (installDir: string) => invoke<void>("install_bepinex", { installDir }),
  uninstallBepinex: (installDir: string) => invoke<void>("uninstall_bepinex", { installDir }),
  installMelonloader: (installDir: string) => invoke<void>("install_melonloader", { installDir }),
  uninstallMelonloader: (installDir: string) => invoke<void>("uninstall_melonloader", { installDir }),
  openModsFolder: (installDir: string) => invoke<void>("open_mods_folder", { installDir }),
  installMod: (installDir: string, sourcePath: string) => invoke<ModInfo>("install_mod", { installDir, sourcePath }),
  deleteMod: (installDir: string, fileName: string) => invoke<void>("delete_mod", { installDir, fileName }),

  reorderGames: (ids: string[]) => invoke<void>("reorder_games", { ids }),
  fetchHltbData: (gameId: string, gameName: string) => invoke<HltbData | null>("fetch_hltb_data", { gameId, gameName }),
  getWeeklyPlaytime: () => invoke<WeeklyPlaytime[]>("get_weekly_playtime"),
  batchUpdateGames: (ids: string[], status?: string, rating?: number, tagsToAdd?: string[]) =>
    invoke<void>("batch_update_games", { ids, status, rating, tagsToAdd }),

  getLibraryGrowth: () => invoke<LibraryGrowthEntry[]>("get_library_growth"),
  fetchIgdbMetadata: (gameId: string, gameName: string, clientId: string, clientSecret: string) =>
    invoke<IgdbMetadata | null>("fetch_igdb_metadata", { gameId, gameName, clientId, clientSecret }),
  clearIgdbData: (id: string) => invoke<void>("clear_igdb_data", { id }),

  getCollections: () => invoke<Collection[]>("get_collections"),
  createCollection: (name: string) => invoke<Collection>("create_collection", { name }),
  renameCollection: (id: string, name: string) => invoke<void>("rename_collection", { id, name }),
  deleteCollection: (id: string) => invoke<void>("delete_collection", { id }),
  getCollectionGames: (collectionId: string) => invoke<Game[]>("get_collection_games", { collectionId }),
  addGameToCollection: (collectionId: string, gameId: string) => invoke<void>("add_game_to_collection", { collectionId, gameId }),
  removeGameFromCollection: (collectionId: string, gameId: string) => invoke<void>("remove_game_from_collection", { collectionId, gameId }),
  getCollectionsForGame: (gameId: string) => invoke<Collection[]>("get_collections_for_game", { gameId }),
  updateCollectionDescription: (id: string, description: string | null) => invoke<void>("update_collection_description", { id, description }),

  syncSteamPlaytime: (apiKey: string, steamId: string) => invoke<SteamSyncResult>("sync_steam_playtime", { apiKey, steamId }),
  pullUninstalledSteamGames: (apiKey: string, steamId: string) => invoke<PullUninstalledResult>("pull_uninstalled_steam_games", { apiKey, steamId }),
  getLogContents: () => invoke<string[]>("get_log_contents"),
  saveSetting: (key: string, value: string) => invoke<void>("save_setting", { key, value }),
  getYearInReview: (year: number) => invoke<YearInReview>("get_year_in_review", { year }),

};
